server:
  port: 8080

spring:
  application:
    name: menu-system
  datasource:
    url: jdbc:postgresql://localhost:5432/menudb
    username: hero_user
    password: super_secure_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true